name:                slackell
version:             0.1.0
homepage:            https://github.com/matsubara0507/slackell#readme
license:             MIT
author:              MATSUBARA Nobutada
maintainer:          t12307043@gunma-u.ac.jp
copyright:           MATSUBARA Nobutada
category:            Web
description:         Please see the README on GitHub at <https://github.com/matsubara0507/slackell#readme>

extra-source-files:
- README.md
- CHANGELOG.md

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

default-extensions:
- ConstraintKinds
- DataKinds
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- LambdaCase
- OverloadedLabels
- OverloadedStrings
- PolyKinds
- RankNTypes
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators
- TypeSynonymInstances

dependencies:
- aeson
- base >= 4.7 && < 5
- base64-bytestring-type
- bytestring
- cryptonite
- extensible >= 0.6.0
- extensible-http-api-data
- http-api-data
- http-media
- memory
- microlens
- req >= 2.0.0
- servant >= 0.4.0
- simple-api
- text
- unordered-containers

library:
  source-dirs: src

tests:
  spec:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - slackell
    - servant-server
    - tasty
    - tasty-hspec
    - warp
