name: Verify

on:
  pull_request: null
  push:
    branches:
    - master

jobs:
  build:
    name: ghc ${{ matrix.ghc }}
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        ghc: ["8.4.4", "8.6.5", "8.8.1"]
        cabal: ["3.0"]
      fail-fast: false

    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1

    - name: Cache .cabal
      uses: actions/cache@v1.1.0
      with:
        path: ~/.cabal
        key: ${{ matrix.ghc }}-cabal-${{ hashFiles('**/slackell.cabal') }}
        restore-keys: |
          ${{ matrix.ghc }}-cabal-
    - uses: actions/setup-haskell@v1
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Install dependencies
      run: |
        cabal v2-update
        cabal v2-build --only-dependencies
    - name: Build & test
      run: |
        cabal v2-build
        cabal v2-test

    - name: Build example
      run: |
        cd example
        cabal v2-build
